### ISSUE TITLE
Creating a compartment then using that compartment ID in the creation of a VCN fails

### ISSUE THREAD

**Issue by sekka1** [oracle/terraform-provider-baremetal#109]
## Description of the bug:

Creating a compartment then using that compartment ID in the creation of a VCN fails.

As a work around, running the same Terraform a second time it succeeds.

```
$ ~/Downloads/terraform_0.9.4 apply .
baremetal_identity_compartment.Compartment: Refreshing state... (ID: ocid1.compartment.oc1..aaaaaaaa2czk6lsa...x5o4ku4twdp3flzlaznxyruat66vff7msqaphq)
baremetal_core_virtual_network.CompleteVCN: Refreshing state... (ID: ocid1.vcn.oc1.phx.aaaaaaaaj5r46lyeyk7sgxkxeqh5uyv7jeddl2ggln2yqpxwkqbfdpb2xvcq)
baremetal_core_virtual_network.CompleteVCN: Destroying... (ID: ocid1.vcn.oc1.phx.aaaaaaaaj5r46lyeyk7sgxkxeqh5uyv7jeddl2ggln2yqpxwkqbfdpb2xvcq)
baremetal_core_virtual_network.CompleteVCN: Destruction complete
baremetal_identity_compartment.Compartment: Destroying... (ID: ocid1.compartment.oc1..aaaaaaaa2czk6lsa...x5o4ku4twdp3flzlaznxyruat66vff7msqaphq)
baremetal_identity_compartment.Compartment: Destruction complete
baremetal_identity_compartment.Compartment: Creating...
  compartment_id: "" => "<computed>"
  description:    "" => "test9"
  inactive_state: "" => "<computed>"
  name:           "" => "test9"
  state:          "" => "<computed>"
  time_created:   "" => "<computed>"
  time_modified:  "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* baremetal_identity_compartment.Compartment: 1 error(s) occurred:

* baremetal_identity_compartment.Compartment: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9e4cb9]
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: goroutine 95 [running]:
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: main.(*CompartmentResourceCrud).ID(0xc4202c1680, 0xc4202c1680, 0x45d964b800)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_identity_compartment.go:70 +0x9
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/crud.CreateResource(0xc42011c9a0, 0xf21f40, 0xc4202c1680, 0x7f291547e250, 0xc420345480)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:95 +0x298
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: main.createCompartment(0xc42011c9a0, 0xb7ac20, 0xc420345480, 0x0, 0xc42035caa8)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_identity_compartment.go:37 +0xc8
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420594780, 0xc4204b8a50, 0xc420497020, 0xb7ac20, 0xc420345480, 0x1, 0x28, 0xc42028ed80)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4200b7ea0, 0xc4204b8a00, 0xc4204b8a50, 0xc420497020, 0x7f29154d5000, 0x0, 0x5950b6a2b5637dc2)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4204a4260, 0xc420496f20, 0xc42048b4c0, 0x0, 0x0)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: reflect.Value.call(0xc42025e2a0, 0xc42000c4e0, 0x13, 0xb7c059, 0x4, 0xc4201d7f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: reflect.Value.Call(0xc42025e2a0, 0xc42000c4e0, 0x13, 0xc4204caf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: net/rpc.(*service).call(0xc42001cac0, 0xc42001c6c0, 0xc420494440, 0xc420344a00, 0xc42050dfc0, 0xa55720, 0xc420496f20, 0x16, 0xa55760, 0xc42048b4c0, ...)
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: created by net/rpc.(*Server).ServeCodec
2017/05/17 16:09:25 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2017/05/17 16:09:25 [DEBUG] plugin: /home/gee/Downloads/terraform_linux_v1.0.10/linux_amd64/terraform-provider-baremetal: plugin process exited
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalIf
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/05/17 16:09:25 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/05/17 16:09:25 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_identity_compartment.Compartment: unexpected EOF
2017/05/17 16:09:25 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_identity_compartment.Compartment: unexpected EOF
2017/05/17 16:09:25 [TRACE] [walkApply] Exiting eval tree: baremetal_identity_compartment.Compartment
2017/05/17 16:09:25 [DEBUG] dag/walk: upstream errored, not walking "baremetal_core_virtual_network.CompleteVCN"
2017/05/17 16:09:25 [DEBUG] dag/walk: upstream errored, not walking "provider.baremetal (close)"
2017/05/17 16:09:25 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/05/17 16:09:25 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/05/17 16:09:25 [TRACE] Preserving existing state lineage "1bb34d0d-29bc-4c0f-bee2-47922a0c430e"
2017/05/17 16:09:25 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/17 16:09:25 [WARN] plugin: error closing client during Kill: connection is shut down



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

## A self-contained terraform file that reproduces the issue:

```

resource "baremetal_identity_compartment" "Compartment" {
    name = "my-compartment"
    description = "my-compartment"
}


resource "baremetal_core_virtual_network" "CompleteVCN" {
  cidr_block = "10.0.0.0/16"
  compartment_id = "${baremetal_identity_compartment.Compartment.id}"
  display_name = "my-vcn"
  dns_label = "my-vcn"
}
```

**Comment by jwolski2** [comment]
I did a bit of deep diving into this issue and think I've found why compartment creation doesn't work. Here are my findings:

The panic occurs in `crud/helpers.go`:

```
// ID is required for state refresh
d.SetId(sync.ID())

if stateful, ok := sync.(StatefullyCreatedResource); ok {
    e = waitForStateRefresh(stateful, d.Timeout(schema.TimeoutCreate), stateful.CreatedPending(), stateful.CreatedTarg  et(), DelayCreate)
}

d.SetId(sync.ID())
```

Above, the first call to `sync.ID()` works fine. The second call panics. The reason is that the call in between (to `waitForStateRefresh()`) unsets the `CompartmentResourceCrud`s `Res` field (from `resource_obmcs_identity_compartment.go`):

```
func (s *CompartmentResourceCrud) ID() string {
    return s.Res.ID
}
```

The question is: why does the call to `waitForStateRefresh` unset it? If you trace what happens in `waitForStateRefresh()`, you'll see there's a call to `sync.Get()`. `Get()` essentially attempts to fetch the compartment resource from the OBMCS API. However, a `Get()` right after a `Create()` likely occurs "too quickly" for the API to return the correct result for the just-created-compartment. You can test this out yourself using the OBMCS CLI. See here:

```
/ # bmcs iam compartment create -c YOUR_TENANCY_OCID_HERE --name bug7 --description bug7 | jq .data.id | sed 's/"//g' | xargs -n1 -I % bmcs iam compartment get -c %
ServiceError:
{
    "code": "NotAuthorizedOrNotFound",
    "message": "Authorization failed or requested resource not found",
    "opc-request-id": "8F1F4C2B554D48DBBCCFB72C5F484C42/367947955EC942738773B19A709A8D62/FF09D8A1CB954AF8802200F448BCB3D6",
    "status": 404
}
```

If you wait a few seconds and retry `bmcs compartment get` again, you'll likely see a positive result:

```
/ # bmcs iam compartment get -c ocid1.compartment.oc1..aaaaaaaajrkj7c3oruxwewf5yqj3hazactbw32xx5dkf5mwglwzxrr4te63a
{
  "data": {
    "compartment-id": "COMPARTMENT_ID_ELIDED",
    "description": "bug7",
    "id": "COMPARTMENT_ID_ELIDED",
    "inactive-status": null,
    "lifecycle-state": "ACTIVE",
    "name": "bug7",
    "time-created": "2017-05-24T10:04:12.050000+00:00"
  },
  "etag": "ETAG_ELIDED"
}
```

Ok, back to the provider. A very quickfix is the one following:

```
diff --git a/crud/helpers.go b/crud/helpers.go
index e950389..8912020 100644
--- a/crud/helpers.go
+++ b/crud/helpers.go
@@ -17,6 +17,11 @@ import (
        "strconv"
 )

+const (
+       DelayCreate  = time.Duration(30 * time.Second)
+       DelayDefault = time.Duration(0 * time.Second)
+)
+
 var (
        FiveMinutes    time.Duration = 5 * time.Minute
        TwoHours       time.Duration = 120 * time.Minute
@@ -151,7 +156,7 @@ func CreateResource(d *schema.ResourceData, sync ResourceCreator) (e error) {
        d.SetId(sync.ID())

        if stateful, ok := sync.(StatefullyCreatedResource); ok {
-               e = waitForStateRefresh(stateful, d.Timeout(schema.TimeoutCreate), stateful.CreatedPending(), stateful.CreatedTarget())
+               e = waitForStateRefresh(stateful, d.Timeout(schema.TimeoutCreate), stateful.CreatedPending(), stateful.CreatedTarget(), DelayCreate)
        }

        d.SetId(sync.ID())
@@ -195,7 +200,7 @@ func DeleteResource(d *schema.ResourceData, sync ResourceDeleter) (e error) {
        }

        if stateful, ok := sync.(StatefullyDeletedResource); ok {
-               e = waitForStateRefresh(stateful, d.Timeout(schema.TimeoutDelete), stateful.DeletedPending(), stateful.DeletedTarget())
+               e = waitForStateRefresh(stateful, d.Timeout(schema.TimeoutDelete), stateful.DeletedPending(), stateful.DeletedTarget(), DelayDefault)

        }

@@ -230,13 +235,14 @@ func stateRefreshFunc(sync StatefulResource) resource.StateRefreshFunc {
 //
 // sync.D.Id must be set.
 // It does not set state from that refreshed state.
-func waitForStateRefresh(sync StatefulResource, timeout time.Duration, pending, target []string) (e error) {
+func waitForStateRefresh(sync StatefulResource, timeout time.Duration, pending, target []string, delay time.Duration) (e error) {
        // TODO: try to move this onto sync
        stateConf := &resource.StateChangeConf{
                Pending: pending,
                Target:  target,
                Refresh: stateRefreshFunc(sync),
                Timeout: timeout,
+               Delay:   delay,
        }

        if _, e = stateConf.WaitForState(); e != nil {
```

What the above fix does is simply pass in a "delay" value into Terraform that tells Terraform to wait before first attempting to refresh. Obviously, this is not a long-term solution, but delaying the call to `Get()` as referenced above does in fact fix _our problem_.

**Comment by jwolski2** [comment]
Came up with a "slightly better fix":

```
diff --git a/crud/helpers.go b/crud/helpers.go
index e950389..d0769e0 100644
--- a/crud/helpers.go
+++ b/crud/helpers.go
@@ -12,7 +12,8 @@ import (
        "github.com/hashicorp/terraform/helper/schema"

        "github.com/oracle/terraform-provider-baremetal/client"
-       "github.com/MustWin/baremetal-sdk-go"
+       baremetal "github.com/MustWin/baremetal-sdk-go"
+
        "errors"
        "strconv"
 )
@@ -215,6 +216,11 @@ func DeleteResource(d *schema.ResourceData, sync ResourceDeleter) (e error) {
 func stateRefreshFunc(sync StatefulResource) resource.StateRefreshFunc {
        return func() (res interface{}, s string, e error) {
                if e = sync.Get(); e != nil {
+              // If it's an expected baremetal.Error, keep on refreshing by
+              // returning back to Terraform all nils.
+              if _, ok := e.(*baremetal.Error); ok {
+                  return nil, "", nil
+              }
                        return nil, "", e
                }
                // We don't set all the state here, because not found errors are handled elsewhere.
```

**Comment by jwolski2** [comment]
We're still testing with the latest fix mentioned. Will update when we've proven or disproven reliability.

**Comment by craigcarl-oracle** [comment]
Bug in the service, fix is being works.

**Comment by jwolski2** [comment]
@craigcarl-oracle By 'bug in the service', do you mean the bug exists server-side and is being fixed there?

**Comment by sriram00** [comment]
Can we create VCN in the default root compartment using terraform , if so should we leave the value of compartment_ocid = " " as null in the env variables ?

**Comment by rcohenma** [comment]
This issue is no longer present in v1.0.14+
