### ISSUE TITLE
load balancer backend set cannot be created

### ISSUE THREAD

**Issue by tomzepf-oracle** [oracle/terraform-provider-baremetal#85]
## Description of the bug:

Several bugs in here:

1) The first example "bes-without" dies as follows:

```
[Error applying plan:

1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-without: 1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-without: Code: InvalidParameter; OPC Request ID: /6763A496FD9F41EF84C293EA44E89479/777333C2AC78486FA57C91ECA06CF5A5; Message: No enum constant com.oracle.pic.flamingo.model.LoadBalancer.Protocol.](url)
```

2) The second example "bes-http" dies as follows:

```
Error applying plan:

1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-http: 1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-http: Code: InvalidParameter; OPC Request ID: /126B76DC6AA940ACAE8BC54AE556370B/F7C262C48C954A38B2ECCFD7D8C5F6AC; Message: URL path must be provided for HTTP health checks
```

There appears to be no way to specify the missing "URL path".

3) The third example should not require the `response_body_regex` and crashes terraform with:

```
Error applying plan:

1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-tcp: 1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-tcp: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: BackendSet Resource is nil, cannot SetData
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: goroutine 105 [running]:
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/lb.(*LoadBalancerBackendSetResourceCrud).SetData(0xc0424250c0)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/lb/backend_set_resource_crud.go:126 +0xf1c
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/crud.CreateResource(0xc042009c00, 0xf441e0, 0xc0424250c0, 0x18b91b0, 0xc04204d380)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:96 +0x2de
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/lb.createLoadBalancerBackendSet(0xc042009c00, 0xb8ef00, 0xc04204d380, 0x0, 0x0)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/lb/backend_set_resource.go:53 +0xc0
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc04229ef00, 0xc042382780, 0xc0422ae0a0, 0xb8ef00, 0xc04204d380, 0x1, 0x28, 0xc0422d9320)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x494
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc042009730, 0xc042382730, 0xc042382780, 0xc0422ae0a0, 0x17f0490, 0x0, 0x0)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0xa2
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc042385160, 0xc042385980, 0xc0423ee390, 0x0, 0x0)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x5e
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: reflect.Value.call(0xc04221be60, 0xc04218a678, 0x13, 0xb9041e, 0x4, 0xc04202ff20, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /usr/local/go/src/reflect/value.go:434 +0x926
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: reflect.Value.Call(0xc04221be60, 0xc04218a678, 0x13, 0xc04202ff20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /usr/local/go/src/reflect/value.go:302 +0xab
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: net/rpc.(*service).call(0xc0421d1500, 0xc0421d14c0, 0xc0421ca6f0, 0xc04204c200, 0xc04234e3c0, 0xa6a4e0, 0xc042385980, 0x16, 0xa6a520, 0xc0423ee390, ...)
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /usr/local/go/src/net/rpc/server.go:387 +0x14b
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe: created by net/rpc.(*Server).ServeCodec
2017/05/02 16:19:58 [DEBUG] plugin: terraform-provider-baremetal.exe:   /usr/local/go/src/net/rpc/server.go:481 +0x40b
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalIf
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/05/02 16:19:58 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/05/02 16:19:58 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-tcp: unexpected EOF
2017/05/02 16:19:58 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_load_balancer_backendset.bes-tcp: unexpected EOF
2017/05/02 16:19:58 [TRACE] [walkApply] Exiting eval tree: baremetal_load_balancer_backendset.bes-tcp
2017/05/02 16:19:58 [DEBUG] dag/walk: upstream errored, not walking "provider.baremetal (close)"
2017/05/02 16:19:58 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/05/02 16:19:58 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/05/02 16:19:58 [TRACE] Preserving existing state lineage "05db7817-dc26-4b8b-8e15-2a3de821792e"
2017/05/02 16:19:58 [DEBUG] plugin: C:\Users\tzepf\exe\terraform-provider-baremetal.exe: plugin process exited
2017/05/02 16:19:58 [TRACE] Preserving existing state lineage "05db7817-dc26-4b8b-8e15-2a3de821792e"
2017/05/02 16:19:58 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/02 16:19:58 [WARN] plugin: error closing client during Kill: connection is shut down
2017/05/02 16:19:58 [DEBUG] plugin: terraform.exe: local-exec-provisioner (internal) 2017/05/02 16:19:58 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/02 16:19:58 [ERR] yamux: Failed to read stream data: read tcp 127.0.0.1:11560->127.0.0.1:10001: wsarecv: An existing connection was forcibly closed by the remote host.
2017/05/02 16:19:58 [ERR] yamux: Failed to write header: write tcp 127.0.0.1:11560->127.0.0.1:10001: use of closed network connection
2017/05/02 16:19:58 [WARN] plugin: error closing client during Kill: unexpected EOF
2017/05/02 16:19:58 [DEBUG] plugin: C:\Users\tzepf\exe\terraform.exe: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

## A self-contained terraform file that reproduces the issue:

```
resource "baremetal_load_balancer_backendset" "bes-without" {
  name             = "bes-without"
  load_balancer_id = "${baremetal_load_balancer.lbtest.id}"
  policy           = "ROUND_ROBIN"
}

resource "baremetal_load_balancer_backendset" "bes-http" {
  name             = "bes-http"
  load_balancer_id = "${baremetal_load_balancer.lbtest.id}"
  policy           = "ROUND_ROBIN"

  health_checker {
    port                = "80"
    protocol            = "HTTP"
    response_body_regex = ".*"
  }
}

resource "baremetal_load_balancer_backendset" "bes-tcp" {
  name             = "bes-tcp"
  load_balancer_id = "${baremetal_load_balancer.lbtest.id}"
  policy           = "ROUND_ROBIN"

  health_checker {
    port     = "80"
    protocol = "TCP"
    response_body_regex = ".*" # FIXME: this should not be needed
  }
}

resource "baremetal_load_balancer" "lbtest" {
  display_name   = "lbtest"
  shape          = "400Mbps"
  compartment_id = "${var.compartment_ocid}"

  subnet_ids = [
    "${baremetal_core_subnet.public0.id}",
    "${baremetal_core_subnet.public1.id}",
  ]
}

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}

provider "baremetal" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

resource "baremetal_core_virtual_network" "lbtest" {
  display_name   = "lbtest"
  dns_label      = "lbtest"
  compartment_id = "${var.compartment_ocid}"
  cidr_block     = "10.0.0.0/16"
}

resource "baremetal_core_internet_gateway" "lbtest" {
  display_name   = "lbtest"
  compartment_id = "${baremetal_core_virtual_network.lbtest.compartment_id}"
  vcn_id         = "${baremetal_core_virtual_network.lbtest.id}"
}

resource "baremetal_core_route_table" "lbtest" {
  display_name   = "lbtest"
  compartment_id = "${baremetal_core_virtual_network.lbtest.compartment_id}"
  vcn_id         = "${baremetal_core_virtual_network.lbtest.id}"

  route_rules {
    cidr_block        = "0.0.0.0/0"
    network_entity_id = "${baremetal_core_internet_gateway.lbtest.id}"
  }
}

resource "baremetal_core_security_list" "public" {
  display_name   = "public"
  compartment_id = "${baremetal_core_virtual_network.lbtest.compartment_id}"
  vcn_id         = "${baremetal_core_virtual_network.lbtest.id}"

  egress_security_rules = [{
    protocol    = "all"
    destination = "0.0.0.0/0"
  }]

  ingress_security_rules = [
    {
      protocol = "1"
      source   = "0.0.0.0/0"

      icmp_options {
        "type" = 3
        "code" = 4
      }
    },
    {
      protocol = "6"
      source   = "0.0.0.0/0"

      tcp_options {
        "max" = 22
        "min" = 22
      }
    },
    {
      protocol = "6"
      source   = "0.0.0.0/0"

      tcp_options {
        "max" = 80
        "min" = 80
      }
    },
    {
      protocol = "6"
      source   = "0.0.0.0/0"

      tcp_options {
        "max" = 443
        "min" = 443
      }
    },
  ]
}

data "baremetal_identity_availability_domains" "lbtest" {
  compartment_id = "${var.tenancy_ocid}"
}

resource "baremetal_core_subnet" "public0" {
  display_name        = "public0"
  dns_label           = "public0"
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.lbtest.availability_domains[0], "name")}"
  cidr_block          = "10.0.0.0/24"
  compartment_id      = "${baremetal_core_virtual_network.lbtest.compartment_id}"
  vcn_id              = "${baremetal_core_virtual_network.lbtest.id}"
  route_table_id      = "${baremetal_core_route_table.lbtest.id}"
  dhcp_options_id     = "${baremetal_core_virtual_network.lbtest.default_dhcp_options_id}"
  security_list_ids   = ["${baremetal_core_security_list.public.id}"]

  # FIXME: workaround for race condition in API
  provisioner "local-exec" {
    command = "sleep 10"
  }
}

resource "baremetal_core_subnet" "public1" {
  display_name        = "public1"
  dns_label           = "public1"
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.lbtest.availability_domains[1], "name")}"
  cidr_block          = "10.0.1.0/24"
  compartment_id      = "${baremetal_core_virtual_network.lbtest.compartment_id}"
  vcn_id              = "${baremetal_core_virtual_network.lbtest.id}"
  route_table_id      = "${baremetal_core_route_table.lbtest.id}"
  dhcp_options_id     = "${baremetal_core_virtual_network.lbtest.default_dhcp_options_id}"
  security_list_ids   = ["${baremetal_core_security_list.public.id}"]

  # FIXME: workaround for race condition in API
  provisioner "local-exec" {
    command = "sleep 10"
  }
}
```

**Comment by sekka1** [comment]
+1

**Comment by tomzepf-oracle** [comment]
Into which release has this been integrated? 1.0.11 is still broken.

In a related question, how can one easily determine which release contains a fix?

**Comment by sekka1** [comment]
I can confirm it still doesnt work.

**Comment by craigcarl-oracle** [comment]
Reopened, being worked on.

**Comment by codycushing** [comment]
Empty cert blocks will no longer break backend set creation, v1.0.12

**Comment by sekka1** [comment]
Thanks @codycushing

**Comment by jiangok2006** [comment]
This still repo with v1.0.14.

This is my tf file:

`resource "baremetal_load_balancer" "port80_load_balancer" {
  shape          = "100Mbps"
  compartment_id = "${var.compartment_ocid}"
  subnet_ids     = ["${baremetal_core_subnet.subnet1.id}", "${baremetal_core_subnet.subnet2.id}"]
  display_name   = "port80_load_balancer"
}


resource "baremetal_load_balancer_backendset" "port80_load_balancer_backendset" {
  load_balancer_id = "${baremetal_load_balancer.port80_load_balancer.id}"
  name             = "port80_load_balancer_backendset"
  policy           = "ROUND_ROBIN"
}

resource "baremetal_load_balancer_backend" "port80_inst1_load_balancer_backend" {
  load_balancer_id = "ocid1.loadbalancer.stub_id"
  backendset_name  = "${baremetal_load_balancer_backendset.port80_load_balancer_backendset.name}"
  name             = "port80_inst1_load_balancer_backend"
  ip_address       = "${module.inst1_mod.inst_ip}"
  port             = 80
  backup           = true
  drain            = true
  offline          = true
  weight           = 1
}`

Any idea?

**Comment by kocic11** [comment]
Change the load balancer id for backend resource. It is still stub_id.

Regards,
Aleksandar

**Comment by jiangok2006** [comment]
Thanks. I did that but no use.

**Comment by codycushing** [comment]
@jiangok2006 there isnt a "name" param for backends. I recommend making sure you are using the most recent provider version--if you are not sure you can execute the plugin binary directly and it will print the version. I also recommend you start from one of the examples here:
https://github.com/oracle/terraform-provider-baremetal/tree/master/docs/examples/load_balancer
